// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/DailyUseChart.tsx";
import * as $1 from "./routes/Past10DaysUserDataChart.tsx";
import * as $2 from "./routes/TotalUseChart.tsx";
import * as $3 from "./routes/_middleware.ts";
import * as $4 from "./routes/api/click.ts";
import * as $5 from "./routes/api/clickData.ts";
import * as $6 from "./routes/api/globalClickData.ts";
import * as $7 from "./routes/api/joke.ts";
import * as $8 from "./routes/api/login.ts";
import * as $9 from "./routes/api/profile.ts";
import * as $10 from "./routes/api/profile/auth/github.ts";
import * as $11 from "./routes/api/profile/auth/google.ts";
import * as $12 from "./routes/api/signout.ts";
import * as $13 from "./routes/api/unclick.ts";
import * as $14 from "./routes/checklist.tsx";
import * as $15 from "./routes/developers.tsx";
import * as $16 from "./routes/index.tsx";
import * as $17 from "./routes/philosophy.tsx";
import * as $18 from "./routes/profile.tsx";
import * as $$0 from "./islands/Checklist.tsx";
import * as $$1 from "./islands/ChecklistItem.tsx";
import * as $$2 from "./islands/Header.tsx";
import * as $$3 from "./islands/Profile.tsx";
import * as $$4 from "./islands/Signup.tsx";

const manifest = {
  routes: {
    "./routes/DailyUseChart.tsx": $0,
    "./routes/Past10DaysUserDataChart.tsx": $1,
    "./routes/TotalUseChart.tsx": $2,
    "./routes/_middleware.ts": $3,
    "./routes/api/click.ts": $4,
    "./routes/api/clickData.ts": $5,
    "./routes/api/globalClickData.ts": $6,
    "./routes/api/joke.ts": $7,
    "./routes/api/login.ts": $8,
    "./routes/api/profile.ts": $9,
    "./routes/api/profile/auth/github.ts": $10,
    "./routes/api/profile/auth/google.ts": $11,
    "./routes/api/signout.ts": $12,
    "./routes/api/unclick.ts": $13,
    "./routes/checklist.tsx": $14,
    "./routes/developers.tsx": $15,
    "./routes/index.tsx": $16,
    "./routes/philosophy.tsx": $17,
    "./routes/profile.tsx": $18,
  },
  islands: {
    "./islands/Checklist.tsx": $$0,
    "./islands/ChecklistItem.tsx": $$1,
    "./islands/Header.tsx": $$2,
    "./islands/Profile.tsx": $$3,
    "./islands/Signup.tsx": $$4,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
